export const types = {
    // roles.controller - getRoles
    LIST_ROLE: 'ROLE/LIST/REQUEST',
    LIST_ROLE_SUCCESS: 'ROLE/LIST/SUCCESS',
    LIST_ROLE_FAILURE: 'ROLE/LIST/FAILURE',
    // roles.controller - getRoleById
    GET_ROLE: 'ROLE/GET/REQUEST',
    GET_ROLE_SUCCESS: 'ROLE/GET/SUCCESS',
    GET_ROLE_FAILURE: 'ROLE/GET/FAILURE',
    // roles.controller - createRole
    CREATE_ROLE: 'ROLE/CREATE/REQUEST',
    CREATE_ROLE_SUCCESS: 'ROLE/CREATE/SUCCESS',
    CREATE_ROLE_FAILURE: 'ROLE/CREATE/FAILURE',
    // roles.controller - updateRole
    UPDATE_ROLE: 'ROLE/UPDATE/REQUEST',
    UPDATE_ROLE_SUCCESS: 'ROLE/UPDATE/SUCCESS',
    UPDATE_ROLE_FAILURE: 'ROLE/UPDATE/FAILURE'
};
