export const types = {
    // permissions.controller - getPermissions
    LIST_PERMISSION: 'PERMISSION/LIST/REQUEST',
    LIST_PERMISSION_SUCCESS: 'PERMISSION/LIST/SUCCESS',
    LIST_PERMISSION_FAILURE: 'PERMISSION/LIST/FAILURE',
    // permissions.controller - getPermissionById
    GET_PERMISSION: 'PERMISSION/GET/REQUEST',
    GET_PERMISSION_SUCCESS: 'PERMISSION/GET/SUCCESS',
    GET_PERMISSION_FAILURE: 'PERMISSION/GET/FAILURE',
    // permissions.controller - createPermission
    CREATE_PERMISSION: 'PERMISSION/CREATE/REQUEST',
    CREATE_PERMISSION_SUCCESS: 'PERMISSION/CREATE/SUCCESS',
    CREATE_PERMISSION_FAILURE: 'PERMISSION/CREATE/FAILURE',
    // permissions.controller - updatePermission
    UPDATE_PERMISSION: 'PERMISSION/UPDATE/REQUEST',
    UPDATE_PERMISSION_SUCCESS: 'PERMISSION/UPDATE/SUCCESS',
    UPDATE_PERMISSION_FAILURE: 'PERMISSION/UPDATE/FAILURE'
};
